### ISSUE TITLE
Jogl-back not working with Java 20 [Quick Fix in issue]

### ISSUE THREAD

**Issue by totetmatt** [gephi/viz-engine#7]
On Windows 10 intel, Using recent java version 
```
java -version
java version "20.0.1" 2023-04-18
Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

```
Rasies this exception 
```
Exception in thread "main" com.jogamp.opengl.GLException: Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, 
owner false, NullToolkitLock[obj 0x62e4a03]], idx 0], pfdID 41, ARB-Choosen true,
        requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/4, sample-ext default, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]],
        chosen    GLCaps[wgl vid 41 arb: rgba 8/8/8/0, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/4, sample-ext default, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]]]
        at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:182)
        at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424)
        at com.jogamp.nativewindow.awt.AWTGraphicsConfiguration.create(AWTGraphicsConfiguration.java:104)
        at com.jogamp.newt.awt.NewtCanvasAWT.addNotify(NewtCanvasAWT.java:600)
        at java.desktop/java.awt.Container.addNotify(Container.java:2804)
        at java.desktop/java.awt.Container.addNotify(Container.java:2804)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4846)
        at java.desktop/java.awt.Container.addNotify(Container.java:2804)
        at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:721)
        at java.desktop/java.awt.Container.addNotify(Container.java:2804)
        at java.desktop/java.awt.Window.addNotify(Window.java:791)
        at java.desktop/java.awt.Frame.addNotify(Frame.java:495)
        at java.desktop/java.awt.Window.pack(Window.java:829)
        at org.gephi.viz.engine.demo.Main.start(Main.java:80)
        at org.gephi.viz.engine.demo.Main.main(Main.java:105)

```
Fortunately some fixes has been provided by adding option to jvm at startup : 

https://github.com/jzy3d/jogl/issues/4#issuecomment-1004895538

command to use  : 
```
java --add-exports java.base/java.lang=ALL-UNNAMED  --add-exports java.desktop/sun.awt=ALL-UNNAMED --add-exports java.desktop/sun.java2d=ALL-UNNAMED   -jar -Xmx2048m target\viz-engine-jogl-demo-1.0.0-SNAPSHOT.jar %*
pause
```

**Comment by eduramiba** [comment]
Thanks Matthieu!
